### ISSUE TITLE
Fatal error  'Serialization of 'Closure' is not allowed'

### ISSUE THREAD

**Issue by mattheu** [joehoyle/Time-Stack#4]
I get the following error when using timestack:

Fatal error: Uncaught exception 'Exception' with message 'Serialization of 'Closure' is not allowed' in /srv/www/newton.dev/content/plugins/Time-Stack-Plugin/time-stack.php:41

**Comment by joehoyle** [comment]
Created on the plugin repo: https://github.com/joehoyle/Time-Stack-Plugin/issues/3
